apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: panchaleswar/argocd-demo
  newTag: af66d7011499f194c582c36d6976fafb8284f87e
resources:
- namespace.yaml
- ../base
