apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: panchaleswar/argocd-demo
  newTag: 9f4ac31df4e9290c0bba228712f9f19b6519dba9
resources:
- ../base
